### ISSUE TITLE
Erro após atualização

### ISSUE THREAD

**Issue by mlisboas** [renatofmmaia/bomb-bot#130]
Amigos,

Após a atualização de hoje, o Bot parou de funcionar e exibe os logs abaixo:
Pode me ajudar?

[04-12 17:09] => Traceback (most recent call last):
  File "main.py", line 63, in main
    manager.do_what_needs_to_be_done(current_screen)
  File "/home/ubuntu/Bomb/module/manager.py", line 38, in do_what_needs_to_be_done
    Hero.do_check_error(self)
  File "/home/ubuntu/Bomb/module/bombScreen.py", line 303, in do_check_error
    BombScreen.go_to_treasure_hunt(manager)
  File "/home/ubuntu/Bomb/module/bombScreen.py", line 126, in go_to_treasure_hunt
    BombScreen.wait_for_screen(BombScreenEnum.TREASURE_HUNT.value)
  File "/home/ubuntu/Bomb/module/bombScreen.py", line 41, in wait_for_screen
    raise Exception(f'Timeout waiting for screen {BombScreenEnum(bombScreenEnum).name}.')
Exception: Timeout waiting for screen TREASURE_HUNT.

[04-12 17:11] => Traceback (most recent call last):
  File "main.py", line 63, in main
    manager.do_what_needs_to_be_done(current_screen)
  File "/home/ubuntu/Bomb/module/manager.py", line 38, in do_what_needs_to_be_done
    Hero.do_check_error(self)
  File "/home/ubuntu/Bomb/module/bombScreen.py", line 303, in do_check_error
    BombScreen.go_to_treasure_hunt(manager)
  File "/home/ubuntu/Bomb/module/bombScreen.py", line 126, in go_to_treasure_hunt
    BombScreen.wait_for_screen(BombScreenEnum.TREASURE_HUNT.value)
  File "/home/ubuntu/Bomb/module/bombScreen.py", line 41, in wait_for_screen
    raise Exception(f'Timeout waiting for screen {BombScreenEnum(bombScreenEnum).name}.')
Exception: Timeout waiting for screen TREASURE_HUNT.

**Comment by mlisboas** [comment]
Já existe outra issue

**Comment by Dailtim** [comment]
Tem que substituir a imagem "identify_treasure_hunt.png" que fica na pasta "assets\images\targets".

Mudou o espaçamento entre os ícones.

**Comment by mlisboas** [comment]
Valeu amigo. Resolvido. Muito obrigado 

Enviado do Yahoo Mail no Android 
 
  Em ter., 12 12e abr. 12e 2022 às 20:02, ***@***.***> escreveu:   


Tem que substituir a imagem "identify_treasure_hunt.png" que fica na pasta "assets\images\targets".

Mudou o espaçamento entre os ícones.
