### ISSUE TITLE
invalid domain os devs blockearam o site pra usar o bot ?

### ISSUE THREAD

**Issue by megamandev** [renatofmmaia/bomb-bot#135]
os devs blockearam o site pra usar o bot ?

https://app.bombcrypto.io/webgl/index.html

ta aparecendo invalid domain

se logar com o bot nessa pagina: https://app.bombcrypto.io/ será que vai dar ban, nessa atualizacao eles colocaram sistema anti-hack que detecta sinais e blockearam o site do bot.
embora esse bot nao seja um hack, gerallment os anti-hack detectam como hack

**Comment by FlavioAlmeida** [comment]
O bot nao funciona na https://app.bombcrypto.io/ da erro ... temos que aguardar uma solucao  :(

**Comment by megamandev** [comment]
a solucao é os devs liberar o acesso ao site https://app.bombcrypto.io/webgl/index.html

**Comment by fpgmat** [comment]
Fala pessoal, instalei a extensão  - https://chrome.google.com/webstore/detail/adblock-%E2%80%94-best-ad-blocker/gighmmpiobklfepjocnamgkkbiglidom

quem não quiser clicar no link, procure a extensão AdBlock
 
é ta funcionando normal o bot. 

abs

**Comment by fpgmat** [comment]
Tem a questão Tb de ver se essa extensão adblock é permitida ou proibida pelo bomb. Fiz aqui e por hora tá rodando. Abs

**Comment by FmKn85** [comment]
Toda semana agora eh uma novidade que quebra tudo :(

De qq forma voces estao usando o link  https://app.bombcrypto.io/  ?

**Comment by megamandev** [comment]
sim

**Comment by FmKn85** [comment]
Aqui nao esta funcionando direito nao :( 
fucniona por pouquissimo tempo e depois fica em loop de refresh nao sei pq

**Comment by megamandev** [comment]
é so vc ajusta a pagina, deixar ben visivel a tela do bomb , bau e herois

**Comment by FmKn85** [comment]
Eh, aqui nao vai. ja fiz de tudo! Passei o dia inteiro nisso!

**Comment by megamandev** [comment]
vai sim, o zoom do navegador tbm tem que estar em 100% e tela do navegador maximixada e a tela onde os bonecos bate tem q esta aparecendo o icone do bau e do heroi

**Comment by megamandev** [comment]
se ainda assim nao resolve d auma olhada nesse topico aqi pode ser q suas imagens estejan desatualizadas

#127

**Comment by FmKn85** [comment]
O de voces mesmo com o navegador em 100% fica uma barra de rolagem na lateral direita e inferoior do frame do jogo? 
que merda isso!

**Comment by gabrielbarbozareal** [comment]
> Fala pessoal, instale a extensão - https://chrome.google.com/webstore/detail/adblock-%E2%80%94-best-ad-blocker/gighmmpiobklfepjocnamgkkbiglidom
> 
> quem não quiser clicar no link, obter uma extensão AdBlock
> 
> está funcionando normal o bot.
> 
> abdômen

essa solução nao funcionou pra mim

**Comment by gabrielbarbozareal** [comment]
> O de voces mesmo com o navegador em 100% fica uma barra de rolagem na lateral direita e inferior do frame do jogo? que merda isso!

vai atualiazando ate sair uma hora ela sai da pagina

**Comment by FmKn85** [comment]
consegui resolver aqui guys!
subrtitui TODAS as imagens com print screens que eu mesmo tirei. estou farmando mais de 24h consecultivas sem diaconnect ou erros com 6 contas!

**Comment by selique** [comment]
> consegui resolver aqui guys! subrtitui TODAS as imagens com print screens que eu mesmo tirei. estou farmando mais de 24h consecultivas sem diaconnect ou erros com 6 contas!

se puder postar as imagens aqui pra subirmos no repositorio seria de grande ajuda eu mesmo farei a resvisao

**Comment by selique** [comment]
[04-18 03:21] => Traceback (most recent call last):
  File "C:\Users\judeu\Projetos\bomb-bot\main.py", line 63, in main
    manager.do_what_needs_to_be_done(current_screen)
  File "C:\Users\judeu\Projetos\bomb-bot\module\manager.py", line 38, in do_what_needs_to_be_done
    Hero.do_check_error(self)
  File "C:\Users\judeu\Projetos\bomb-bot\module\bombScreen.py", line 303, in do_check_error
    BombScreen.go_to_treasure_hunt(manager)
  File "C:\Users\judeu\Projetos\bomb-bot\module\bombScreen.py", line 126, in go_to_treasure_hunt
    BombScreen.wait_for_screen(BombScreenEnum.TREASURE_HUNT.value)
  File "C:\Users\judeu\Projetos\bomb-bot\module\bombScreen.py", line 41, in wait_for_screen
    raise Exception(f'Timeout waiting for screen {BombScreenEnum(bombScreenEnum).name}.')
Exception: Timeout waiting for screen TREASURE_HUNT.

me embasando no erro essa é a imagem que esta dando problema @renatofmmaia se vc puder compartilhar a imagem original sua @FmKn85 vou tentar providenciar o concerto do codigo
![identify_treasure_hunt](https://user-images.githubusercontent.com/1678894/163764850-21563bbd-1ee0-4339-b2f1-31312cf082c2.png)
