### ISSUE TITLE
Exception: Timeout waiting for screen HEROES.

### ISSUE THREAD

**Issue by devdiegofaria** [renatofmmaia/bomb-bot#43]
[02-16 08:00] => Traceback (most recent call last):
  File "D:\bot\bomb-bot\main.py", line 63, in main
    manager.do_what_needs_to_be_done(current_screen)
  File "D:\bot\bomb-bot\module\manager.py", line 46, in do_what_needs_to_be_done
    Hero.who_needs_work(self)
  File "D:\bot\bomb-bot\module\bombScreen.py", line 221, in who_needs_work
    BombScreen.go_to_heroes(manager)
  File "D:\bot\bomb-bot\module\bombScreen.py", line 105, in go_to_heroes
    BombScreen.wait_for_screen(BombScreenEnum.HEROES.value)
  File "D:\bot\bomb-bot\module\bombScreen.py", line 41, in wait_for_screen
    raise Exception(f'Timeout waiting for screen {BombScreenEnum(bombScreenEnum).name}.')
Exception: Timeout waiting for screen HEROES.

**Comment by KcassPr** [comment]
can you send me a screenshot of your screen.

**Comment by andresandri2** [comment]
> [02-16 08:00] => Traceback (most recent call last): File "D:\bot\bomb-bot\main.py", line 63, in main manager.do_what_needs_to_be_done(current_screen) File "D:\bot\bomb-bot\module\manager.py", line 46, in do_what_needs_to_be_done Hero.who_needs_work(self) File "D:\bot\bomb-bot\module\bombScreen.py", line 221, in who_needs_work BombScreen.go_to_heroes(manager) File "D:\bot\bomb-bot\module\bombScreen.py", line 105, in go_to_heroes BombScreen.wait_for_screen(BombScreenEnum.HEROES.value) File "D:\bot\bomb-bot\module\bombScreen.py", line 41, in wait_for_screen raise Exception(f'Timeout waiting for screen {BombScreenEnum(bombScreenEnum).name}.') Exception: Timeout waiting for screen HEROES.

Qual versão do python está instalada? Executou o pip para instalar os requerimentos? A tela do jogo está totalmente visível?

**Comment by Jiffersantos** [comment]
Eh praticamente o mesmo erro que da nos 10 minutos. Aqui também ocorre.
