### ISSUE TITLE
Erro ao executar o main.py (ImportError: DLL load failed...)

### ISSUE THREAD

**Issue by PortesB** [renatofmmaia/bomb-bot#78]
Ao executar o "main.py" recebo este este erro:

c:\bomb-bot-0.0.4>python main.py
Traceback (most recent call last):
  File "c:\bomb-bot-0.0.4\main.py", line 8, in <module>
    from module.bombScreen import BombScreen, BombScreenEnum
  File "c:\bomb-bot-0.0.4\module\bombScreen.py", line 4, in <module>
    from cv2 import cv2
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\cv2\__init__.py", line 8, in <module>
    from .cv2 import *
ImportError: DLL load failed while importing cv2: %1 não é um aplicativo Win32 válido.

**Comment by jhonathannc** [comment]
Instale o pacote do open cv. Vai no terminal do windows e digite:
`pip install opencv-python`

Precisei instalar esse pacote aqui no linux tambem.
