### ISSUE TITLE
Sugestão de Login

### ISSUE THREAD

**Issue by fmnicolas** [renatofmmaia/bomb-bot#82]
Com a nova função do bomb de login por usuário e senha poderia ter a opção de selecionar qual método de login o bot utilizaria.

**Comment by fpgmat** [comment]
Bom dia Renato, complementando a sugestão do colega, qd poe login e senha, os dados ficam gravados no navegador, e o login é muito mais rápido do q usando a metamask, dessa forma, seria mais efetivo o bot acessando pelo login. seria possível fazer o bot logando por login e senha? até pq dessa forma se torma até mais seguro. Abs

**Comment by wsa7** [comment]
Tenho 4 contas na VPS e não esta logando em 1, não teve att no novo botão CONNECT?

**Comment by nobrugoulart** [comment]
> Com a nova função do bomb de login por usuário e senha poderia ter a opção de selecionar qual método de login o bot utilizaria.

Eu fiz essa modificação pois utilizo TREZOR e está em uma VPS, criei 3 escolinhas nas contas e fiz as seguintes modificações no bot:
PRIMEIRO: mudei está imagem ![button_connect_metamask](https://user-images.githubusercontent.com/84783504/156895661-3c1d3539-5115-40c7-a6fd-45c2d7053053.png) pelo que estava da connect pela metamask.

trocar pela assets\images\targets\button_connect_metamask.png

SEGUNDO: modifiquei o código /module/bombScreen.py

 APAGAR TODO ESSE CODIGO (LINHA 192 a 195) 

          logger_translated("sigin wallet", LoggerEnum.BUTTON_CLICK)
                if not click_when_target_appears("button_connect_wallet_sign"):
                    refresh_page()
                    continue


foi deixar o arquivo já modificado caso preferirem:
[bombScreen.zip](https://github.com/renatofmmaia/bomb-bot/files/8191230/bombScreen.zip)

colar em /module

TERCEIRO: faça o login na conta para ficar salvo, após isso inicie o bot.

se te ajudei de alguma forma e quiser me ajudar hihi
0xe30EA30dFdEBFF2B03597AEAC72418c9bca2E3f6

**Comment by fmnicolas** [comment]
baixei e fiz tudo, tive o erro no log: `[03-05 21:15] => Traceback (most recent call last):
  File "C:\bomb-bot\main.py", line 63, in main
    manager.do_what_needs_to_be_done(current_screen)
  File "C:\bomb-bot\module\manager.py", line 38, in do_what_needs_to_be_done
    Hero.do_check_error(self)
  File "C:\bomb-bot\module\bombScreen.py", line 296, in do_check_error
    Login.do_login(manager)
  File "C:\bomb-bot\module\bombScreen.py", line 178, in do_login
    BombScreen.wait_for_screen(BombScreenEnum.LOGIN.value)
  File "C:\bomb-bot\module\bombScreen.py", line 41, in wait_for_screen
    raise Exception(f'Timeout waiting for screen {BombScreenEnum(bombScreenEnum).name}.')
Exception: Timeout waiting for screen LOGIN.` após iniciar, se puder ajudar agradeço, não uso vps

**Comment by dibelt** [comment]
> > Com a nova função do bomb de login por usuário e senha poderia ter a opção de selecionar qual método de login o bot utilizaria.
> 
> Eu fiz essa modificação pois utilizo TREZOR e está em uma VPS, criei 3 escolinhas nas contas e fiz as seguintes modificações no bot: mudei está imagem ![button_connect_metamask](https://user-images.githubusercontent.com/84783504/156895661-3c1d3539-5115-40c7-a6fd-45c2d7053053.png) pelo que estava da connect pela metamask.
> 
> trocar pela assets\images\targets\button_connect_metamask.png
> 
> e modifiquei o código /module/bombScreen.py
> 
> APAGAR TODO ESSE CODIGO (LINHA 192 a 195)
> 
> ```
>       logger_translated("sigin wallet", LoggerEnum.BUTTON_CLICK)
>             if not click_when_target_appears("button_connect_wallet_sign"):
>                 refresh_page()
>                 continue
> ```
> 
> foi deixar o arquivo já modificado caso preferirem: [bombScreen.zip](https://github.com/renatofmmaia/bomb-bot/files/8191230/bombScreen.zip)
> 
> colar em /module
> 
> se te ajudei de alguma forma e quiser me ajudar hihi 0xe30EA30dFdEBFF2B03597AEAC72418c9bca2E3f6

aqui deu certinho isso ae... muito obrigado amigao, se algum dia eu tiver lucro no bomb vou lembrar de vc e vo te mandar uns BUSD e pro renato tambem... vlw tmj

**Comment by nobrugoulart** [comment]
> 

tu colocou o login e logou antes de inciar o bot ?

**Comment by nobrugoulart** [comment]
> 



> baixei e fiz tudo, tive o erro no log: `[03-05 21:15] => Traceback (most recent call last): File "C:\bomb-bot\main.py", line 63, in main manager.do_what_needs_to_be_done(current_screen) File "C:\bomb-bot\module\manager.py", line 38, in do_what_needs_to_be_done Hero.do_check_error(self) File "C:\bomb-bot\module\bombScreen.py", line 296, in do_check_error Login.do_login(manager) File "C:\bomb-bot\module\bombScreen.py", line 178, in do_login BombScreen.wait_for_screen(BombScreenEnum.LOGIN.value) File "C:\bomb-bot\module\bombScreen.py", line 41, in wait_for_screen raise Exception(f'Timeout waiting for screen {BombScreenEnum(bombScreenEnum).name}.') Exception: Timeout waiting for screen LOGIN.` após iniciar, se puder ajudar agradeço, não uso vps

tu colocou o login e depois iniciou o bot ? talvez seja isso. vou deixa meu bot já tudo configurado e tu só precisa logar com suas credências primeiro depois fecha e inicia o bot.
[bomb.zip](https://github.com/renatofmmaia/bomb-bot/files/8192700/bomb.zip)

**Comment by nobrugoulart** [comment]
> 



> > > Com a nova função do bomb de login por usuário e senha poderia ter a opção de selecionar qual método de login o bot utilizaria.
> > 
> > 
> > Eu fiz essa modificação pois utilizo TREZOR e está em uma VPS, criei 3 escolinhas nas contas e fiz as seguintes modificações no bot: mudei está imagem ![button_connect_metamask](https://user-images.githubusercontent.com/84783504/156895661-3c1d3539-5115-40c7-a6fd-45c2d7053053.png) pelo que estava da connect pela metamask.
> > trocar pela assets\images\targets\button_connect_metamask.png
> > e modifiquei o código /module/bombScreen.py
> > APAGAR TODO ESSE CODIGO (LINHA 192 a 195)
> > ```
> >       logger_translated("sigin wallet", LoggerEnum.BUTTON_CLICK)
> >             if not click_when_target_appears("button_connect_wallet_sign"):
> >                 refresh_page()
> >                 continue
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > foi deixar o arquivo já modificado caso preferirem: [bombScreen.zip](https://github.com/renatofmmaia/bomb-bot/files/8191230/bombScreen.zip)
> > colar em /module
> > se te ajudei de alguma forma e quiser me ajudar hihi 0xe30EA30dFdEBFF2B03597AEAC72418c9bca2E3f6
> 
> aqui deu certinho isso ae... muito obrigado amigao, se algum dia eu tiver lucro no bomb vou lembrar de vc e vo te mandar uns BUSD e pro renato tambem... vlw tmj

que bom amigo que deu certo ai, tamo juntoo! bomb é lua!!

**Comment by fmnicolas** [comment]
> > 
> 
> > baixei e fiz tudotivo o error no log `[03-05 21:15] => Traceback (most recent call last): File "C:\bomb-bot\main.py", line 63, in main manager.do_what_needs_to_be_done(current_screen) File "C:\bomb-bot\module\manager.py", line 38, in do_what_needs_to_be_done Hero.do_check_error(self) File "C:\bomb-bot\module\bombScreen.py", line 296, in do_check_error Login.do_login(manager) File "C:\bomb-bot\module\bombScreen.py", line 178, in do_login BombScreen.wait_for_screen(BombScreenEnum.LOGIN.value) File "C:\bomb-bot\module\bombScreen.py", line 41, in wait_for_screen raise Exception(f'Timeout waiting for screen {BombScreenEnum(bombScreenEnum).name}.') Exception: Timeout waiting for screen LOGIN.`após iniciar, se puder ajudar, não uso vps
> 
> tu o login e depois iniciado o bot? talvez seja isso. Vou deixar meu bot já configurado e tu só precisa logar com suas credenciais primeiro depois fechar e iniciar o bot. [bomb.zip](https://github.com/renatofmmaia/bomb-bot/files/8192700/bomb.zip)

Outro problema é que o mouse não mexe, não entendo muito de python

**Comment by nobrugoulart** [comment]
> 



> > > 
> > 
> > 
> > > baixei e fiz tudotivo o error no log `[03-05 21:15] => Traceback (most recent call last): File "C:\bomb-bot\main.py", line 63, in main manager.do_what_needs_to_be_done(current_screen) File "C:\bomb-bot\module\manager.py", line 38, in do_what_needs_to_be_done Hero.do_check_error(self) File "C:\bomb-bot\module\bombScreen.py", line 296, in do_check_error Login.do_login(manager) File "C:\bomb-bot\module\bombScreen.py", line 178, in do_login BombScreen.wait_for_screen(BombScreenEnum.LOGIN.value) File "C:\bomb-bot\module\bombScreen.py", line 41, in wait_for_screen raise Exception(f'Timeout waiting for screen {BombScreenEnum(bombScreenEnum).name}.') Exception: Timeout waiting for screen LOGIN.`após iniciar, se puder ajudar, não uso vps
> > 
> > 
> > tu o login e depois iniciado o bot? talvez seja isso. Vou deixar meu bot já configurado e tu só precisa logar com suas credenciais primeiro depois fechar e iniciar o bot. [bomb.zip](https://github.com/renatofmmaia/bomb-bot/files/8192700/bomb.zip)
> 
> Outro problema é que o mouse não mexe, não entendo muito de python

rodasse pip install -r requirements.txt ?? e seu navegador está com o zoom em 100% ?

**Comment by fmnicolas** [comment]
> > 
> 
> > > > 
> > > 
> > > 
> > > > baixei e fiz tudotivo o error no log `[03-05 21:15] => Traceback (most recent call last): File "C:\bomb-bot\main.py", line 63, in main manager.do_what_needs_to_be_done(current_screen) File "C:\bomb-bot\module\manager.py", line 38, in do_what_needs_to_be_done Hero.do_check_error(self) File "C:\bomb-bot\module\bombScreen.py", line 296, in do_check_error Login.do_login(manager) File "C:\bomb-bot\module\bombScreen.py", line 178, in do_login BombScreen.wait_for_screen(BombScreenEnum.LOGIN.value) File "C:\bomb-bot\module\bombScreen.py", line 41, in wait_for_screen raise Exception(f'Timeout waiting for screen {BombScreenEnum(bombScreenEnum).name}.') Exception: Timeout waiting for screen LOGIN.`após iniciar, se puder ajudar, não uso vps
> > > 
> > > 
> > > tu o login e depois iniciado o bot? talvez seja isso. Vou ativar meu bot já configurado e você só precisa logar com suas credenciais primeiro depois fechar e iniciar o bot. [bomb.zip](https://github.com/renatofmmaia/bomb-bot/files/8192700/bomb.zip)
> > 
> > 
> > Outro problema é que o mouse não mexe, não entendo muito de python
> 
> rodase pip install -r requirements.txt ?? e seu navegador está com o zoom em 100% ?

Sim, instalei os requirements e o zoom está 100%.

**Comment by wsa7** [comment]
> > Com a nova função do bomb de login por usuário e senha poderia ter a opção de selecionar qual método de login o bot utilizaria.
> 
> Eu fiz essa modificação pois utilizo TREZOR e está em uma VPS, criei 3 escolinhas nas contas e fiz as seguintes modificações no bot: PRIMEIRO: mudei está imagem ![button_connect_metamask](https://user-images.githubusercontent.com/84783504/156895661-3c1d3539-5115-40c7-a6fd-45c2d7053053.png) pelo que estava da connect pela metamask.
> 
> trocar pela assets\images\targets\button_connect_metamask.png
> 
> SEGUNDO: modifiquei o código /module/bombScreen.py
> 
> APAGAR TODO ESSE CODIGO (LINHA 192 a 195)
> 
> ```
>       logger_translated("sigin wallet", LoggerEnum.BUTTON_CLICK)
>             if not click_when_target_appears("button_connect_wallet_sign"):
>                 refresh_page()
>                 continue
> ```
> 
> foi deixar o arquivo já modificado caso preferirem: [bombScreen.zip](https://github.com/renatofmmaia/bomb-bot/files/8191230/bombScreen.zip)
> 
> colar em /module
> 
> TERCEIRO: faça o login na conta para ficar salvo, após isso inicie o bot.
> 
> se te ajudei de alguma forma e quiser me ajudar hihi 0xe30EA30dFdEBFF2B03597AEAC72418c9bca2E3f6

obrigado amigo!

**Comment by wsa7** [comment]
> > 
> 
> > > > 
> > > 
> > > 
> > > > baixei e fiz tudotivo o error no log `[03-05 21:15] => Traceback (most recent call last): File "C:\bomb-bot\main.py", line 63, in main manager.do_what_needs_to_be_done(current_screen) File "C:\bomb-bot\module\manager.py", line 38, in do_what_needs_to_be_done Hero.do_check_error(self) File "C:\bomb-bot\module\bombScreen.py", line 296, in do_check_error Login.do_login(manager) File "C:\bomb-bot\module\bombScreen.py", line 178, in do_login BombScreen.wait_for_screen(BombScreenEnum.LOGIN.value) File "C:\bomb-bot\module\bombScreen.py", line 41, in wait_for_screen raise Exception(f'Timeout waiting for screen {BombScreenEnum(bombScreenEnum).name}.') Exception: Timeout waiting for screen LOGIN.`após iniciar, se puder ajudar, não uso vps
> > > 
> > > 
> > > tu o login e depois iniciado o bot? talvez seja isso. Vou deixar meu bot já configurado e tu só precisa logar com suas credenciais primeiro depois fechar e iniciar o bot. [bomb.zip](https://github.com/renatofmmaia/bomb-bot/files/8192700/bomb.zip)
> > 
> > 
> > Outro problema é que o mouse não mexe, não entendo muito de python
> 
> rodasse pip install -r requirements.txt ?? e seu navegador está com o zoom em 100% ?

ele esta bugando, nao da alt tab, com 6 contas

**Comment by ZePela** [comment]
Gente, tem um quarto passo que seria muito útil para alguns:

Chega uma hora, que o bot passa a não reconhecer a imagem do "identify treasure hunt"... Isso se dá pq na imagem ainda consta a moedinha do lado do CHEST e da engrenagem de configuração do game...

Pra quem está logando com login e senha, essa moedinha some... não vai mais estar ali... Não aparece mais os bcoins q estão na sua wallet.

Entao, aconselho abrir a imagem do "identify treasure hunt" e apagar a moedinha, e deixar só o chest e a engrenagem... Assim, seu bot vai parar de desconectar tanto... :)

**Comment by juniorgtxx** [comment]
> Gente, tem um quarto passo que seria muito útil para alguns:
> 
> Chega uma hora, que o bot passa a não reconhecer a imagem do "identify treasure hunt"... Isso se dá pq na imagem ainda consta a moedinha do lado do CHEST e da engrenagem de configuração do game...
> 
> Pra quem está logando com login e senha, essa moedinha some... não vai mais estar ali... Não aparece mais os bcoins q estão na sua wallet.
> 
> Entao, aconselho abrir a imagem do "identify treasure hunt" e apagar a moedinha, e deixar só o chest e a engrenagem... Assim, seu bot vai parar de desconectar tanto... :)

Fiz isso aqui mais ele continua dando erro não acha a imagem ai ele reinicia a pagina.
