### ISSUE TITLE
Ubuntu VM - DISPLAY issue

### ISSUE THREAD

**Issue by mpmafra1403** [renatofmmaia/bomb-bot#87]
root@ubuntu:/bomb# echo $DISPLAY
:0
root@ubuntu:/bomb# python3 main.py 
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from module.bombScreen import BombScreen, BombScreenEnum
  File "/bomb/module/bombScreen.py", line 7, in <module>
    from .image import Image
  File "/bomb/module/image.py", line 11, in <module>
    from .utils import *
  File "/bomb/module/utils.py", line 4, in <module>
    import pyautogui
  File "/usr/local/lib/python3.8/dist-packages/pyautogui/__init__.py", line 249, in <module>
    import mouseinfo
  File "/usr/local/lib/python3.8/dist-packages/mouseinfo/__init__.py", line 223, in <module>
    _display = Display(os.environ['DISPLAY'])
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'DISPLAY'

alguem ja passou por esse problema no linux? estava rodando no windows via VM, porem gostaria de otimizar os recursos com o Linux.

**Comment by arnaldoojunior** [comment]
Olá, tive o mesmo problema, roda com o usuário ubuntu.
