### ISSUE TITLE
erro(help)

### ISSUE THREAD

**Issue by CrazyChappie** [renatofmmaia/bomb-bot#9]
[2022-02-08 19:29:55] => Traceback (most recent call last):
  File "C:\Users\Felipe\OneDrive\Área de Trabalho\bomb-bot-master\main.py", line 63, in main
    manager.do_what_needs_to_be_done(current_screen)
  File "C:\Users\Felipe\OneDrive\Área de Trabalho\bomb-bot-master\module\manager.py", line 46, in do_what_needs_to_be_done
    Hero.who_needs_work(self)
  File "C:\Users\Felipe\OneDrive\Área de Trabalho\bomb-bot-master\module\bombScreen.py", line 266, in who_needs_work
    n_clicks_per_scrool = scroll_and_click_on_targets(
  File "C:\Users\Felipe\OneDrive\Área de Trabalho\bomb-bot-master\module\mouse.py", line 86, in scroll_and_click_on_targets
    res.append(function_between())
  File "C:\Users\Felipe\OneDrive\Área de Trabalho\bomb-bot-master\module\bombScreen.py", line 227, in click_available_heroes
    buttons_position = Image.get_target_positions("button_work_unchecked", not_target="button_work_checked", screen_image=screen_img)
  File "C:\Users\Felipe\OneDrive\Área de Trabalho\bomb-bot-master\module\image.py", line 93, in get_target_positions
    result[result < not_target_result] = 0
ValueError: operands could not be broadcast together with shapes (1052,3240) (1053,3242)

**Comment by CrazyChappie** [comment]
ele loga, abre o campo de mineração, abre os herois ai fica um tempo parado logo apos da esse erro

**Comment by renatofmmaia** [comment]
Fala @CrazyChappie, em qual ambiente você esta executando o bot? VM, VPS, seu próprio pc?
Qual a resolução que você utiliza neste ambiente?

**Comment by CrazyChappie** [comment]
> Fala @CrazyChappie, em qual ambiente você esta executando o bot? VM, VPS, seu próprio pc?
> 
> Qual a resolução que você utiliza neste ambiente?
> 
> 

 
Bom Dia Meu Amigo 
Uso no Próprio pc

1366x768

**Comment by renatofmmaia** [comment]
Deveria funcionar normalmente, você utiliza zoom no Windows? Verifica depois, pode ser o motivo de não ter funcionado na primeira vez...
Vou tentar nessa resolução em windows para ver se acho algum problema.

**Comment by hiagopinacio** [comment]
vc tirou novas prints? as imagens **button_work_unchecked.png** e **button_work_checked.png** devem ter o mesmo tamanho de pixes, tanto na altura quanto na largura.
